### ISSUE TITLE
how to get block size

### ISSUE THREAD

**Issue by MaJun0007** [imgtec/lz4-embedded#1]
i can't understander those codes , can you tell me thanks!
  blocksize  = (unsigned char)p[3] << 0x18U; //why 0x18u!!!!!
  blocksize |= (unsigned char)p[2] << 0x10U;
  blocksize |= (unsigned char)p[1] << 0x08U;
  blocksize |= (unsigned char)p[0] << 0x00U;

**Comment by imgtec** [comment]
这个只是简单地把四个字节组装成一个32位的整数而已啊。
